Linting with Prettier

diff --git a/.github/actions/deploy-environment-aks/action.yml b/.github/actions/deploy-environment-aks/action.yml
--- a/.github/actions/deploy-environment-aks/action.yml
+++ b/.github/actions/deploy-environment-aks/action.yml
@@ -19,38 +19,38 @@ runs:
   using: composite
 
   steps:
-          - uses: hashicorp/setup-terraform@v3
-            with:
-              terraform_version: 1.6.4
-              terraform_wrapper: false
+    - uses: hashicorp/setup-terraform@v3
+      with:
+        terraform_version: 1.6.4
+        terraform_wrapper: false
 
-          - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
-            with:
-              azure-credentials: ${{ inputs.azure-credentials }}
+    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
+      with:
+        azure-credentials: ${{ inputs.azure-credentials }}
 
-          - name: Terraform Apply
-            shell: bash
-            run: |
-              make ci ${{ inputs.environment }} aks-terraform-apply
-            env:
-              DOCKER_IMAGE_TAG: ${{ inputs.image-tag }}
-              PR_NUMBER: ${{ inputs.pull-request-number }}
+    - name: Terraform Apply
+      shell: bash
+      run: |
+        make ci ${{ inputs.environment }} aks-terraform-apply
+      env:
+        DOCKER_IMAGE_TAG: ${{ inputs.image-tag }}
+        PR_NUMBER: ${{ inputs.pull-request-number }}
 
-          - name: Extract Terraform outputs
-            shell: bash
-            id: set_outputs
-            run: |
-              output=$(terraform -chdir=terraform/application output -json urls)
-              echo "HOSTNAMES=$output" >> $GITHUB_ENV
+    - name: Extract Terraform outputs
+      shell: bash
+      id: set_outputs
+      run: |
+        output=$(terraform -chdir=terraform/application output -json urls)
+        echo "HOSTNAMES=$output" >> $GITHUB_ENV
 
-          - name: Run smoke tests
-            shell: bash
-            run: |
-              # Parse the JSON array of URLs into a Bash array
-              urls=$(echo "$HOSTNAMES" | jq -r '.[]')
+    - name: Run smoke tests
+      shell: bash
+      run: |
+        # Parse the JSON array of URLs into a Bash array
+        urls=$(echo "$HOSTNAMES" | jq -r '.[]')
 
-              # Loop over each URL and perform the curl check on the /health/all.json endpoint
-              for url in $urls; do
-                echo "Check health for $url/health/all.json..."
-                curl -sS --fail "$url/health/all.json" > /dev/null && echo "Health check passed for $url" || echo "Health check failed for $url"
-              done
+        # Loop over each URL and perform the curl check on the /health/all.json endpoint
+        for url in $urls; do
+          echo "Check health for $url/health/all.json..."
+          curl -sS --fail "$url/health/all.json" > /dev/null && echo "Health check passed for $url" || echo "Health check failed for $url"
+        done
