Testing smoke tests

diff --git a/.github/actions/deploy-environment-aks/action.yml b/.github/actions/deploy-environment-aks/action.yml
--- a/.github/actions/deploy-environment-aks/action.yml
+++ b/.github/actions/deploy-environment-aks/action.yml
@@ -43,6 +43,18 @@ runs:
               output=$(terraform -chdir=terraform/application output -json urls)
               echo "HOSTNAMES=$output" >> $GITHUB_ENV
 
+          - name: Run smoke tests
+            shell: bash
+            run: |
+              # Parse the JSON array of URLs into a Bash array
+              urls=$(echo "$HOSTNAMES" | jq -r '.[]')
+
+              # Loop over each URL and perform the curl check on the /health/all.json endpoint
+              for url in $urls; do
+                echo "Check health for $url/health/all.json..."
+                curl -sS --fail "$url/health/all.json" > /dev/null && echo "Health check passed for $url" || echo "Health check failed for $url"
+              done
+
           # # Check new site is up
           # - run: |
           #     echo "Checking new site is up"
